### PR TITLE
Multi: fix warning on settings page and make persistent IsLegacy across screens

### LINKED ISSUE #2768: IsLegacy should be persistent across screens
Otherwise leaving then coming back to each individual screen clears it.

### LINKED ISSUE #2770: Settings page throwing error
I get the following console error on the settings page:

```
checkPropTypes.js:20 Warning: Failed prop type: You provided a `checked` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultChecked`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by Checkbox)
    in label (created by Checkbox)
    in Checkbox (created by PrivacySettings)
    in div (created by PrivacySettings)
   ...
 ```

### PR DESCRIPTION
**Pull request by bgptr**
Closes #2770
Closes #2768

### CODE REVIEW

File: app/actions/VSPActions.js [hunk 1]
```diff
@@ -463,3 +463,12 @@ export const discoverAvailableStakepools = () => async (dispatch, getState) => {
 
   return vspInfo;
 };
+
+
```
Comment (vctt94) [inline app/actions/VSPActions.js:467]: extra line

**Review by vctt94 — APPROVED** [review]
Thanks! Those warning were annoying me haha

LGTM
