### PR TITLE
Fix duplicate proposals

### LINKED ISSUE #2269: [1.5.0-rc1] Proposals: Duplicated Spanish marketing proposal
Restarting decrediton resolved this, Im not sure how to recreate it.

Screenshot from 2019-11-08 15-12-25

### PR DESCRIPTION
**Pull request by vctt94**
closes #2269

### CODE REVIEW

File: app/actions/GovernanceActions.js [hunk 1]
```diff
@@ -214,11 +214,25 @@ export const getProposalsAndUpdateVoteStatus = (tokensBatch) => async (dispatch,
...
-    );
-    return newProposals;
+  const concatProposals = (oldProposals, newProposals) => {
+    const response = {};
+    Object.keys(oldProposals).forEach( key => {
+      if (oldProposals[key] && oldProposals[key].length > 0) {
+        for (let i = 0; i < newProposals[key].length; i++) {
+          const newProp = newProposals[key][i];
+          if (findProposal(oldProposals[key], newProp.token)) {
+            oldProposals[key][i] = newProp;
```
Comment (matheusd) [inline app/actions/GovernanceActions.js]: You're modifying `oldProposals` in place, which can cause rendering artifacts.
