### PR TITLE
More allusive passphrase update failed message

### LINKED ISSUE #1694: Error shown if passphrase reset is attempted with wrong passphrase
**Steps to recreate:**
- Open the settings tab
- Click "Update Private Passphrase"
- Enter an incorrect value for current passphrase, and two matching values for the new passphrase.
- Continue

**Expected result**
- A meaningful error informing the user their passphrase was incorrect

**Actual result:**
- An error saying: `TypeError: Cannot read property 'PRIVATE' of undefined`

### PR DESCRIPTION
**Pull request by Jujhar**
Fixes #1694

Now it says "Entered incorrect private passphrase reset blocked."

### CODE REVIEW

File: app/reducers/snackbar.js [hunk 1]
```diff
@@ -156,7 +156,7 @@ const messages = defineMessages({
   },
   CHANGEPASSPHRASE_FAILED: {
     id: "settings.errors.changePassphraseFailed",
-    defaultMessage: "{originalError}"
+    defaultMessage: "Entered incorrect private passphrase reset blocked."
```
Comment (alexlyp) [inline app/reducers/snackbar.js]: This message doesn't make any sense

Comment (Jujhar) [reply app/reducers/snackbar.js]: When you reset the password you are asked for three options first being your old private password and if that is wrong this message comes up.

Maybe its better if it is "Password reset failed entered incorrect previous passphrase"?

Comment (alexlyp) [reply app/reducers/snackbar.js]: I think you're being too verbose.  

"Update password failed.  Incorrect private passphrase, please try again."
