### PR TITLE
[overview] fix: overview page adjustments

### LINKED ISSUE #2679: [responsiveness] overview looks weird in small widths:
The icon which shows the menu active looks weird and we should put the tables in the same column, so we can see them

image

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff fixes some details on overview pages, such as tabs behavior, transactions and stake cards alignment and positioning

Closes #2679 

Screen Shot 2020-10-19 at 9 43 39 PM

### CODE REVIEW

**Review by matheusd — APPROVED** [review]

File: app/components/shared/TabsHeader/index.js [hunk 1]
```diff
@@ -0,0 +1 @@
+export { default } from "./TabsHeader";
```
Comment (vctt94) [inline app/components/shared/TabsHeader/index.js:1]: This index is not necessary, you can use the file directly

**Review by vctt94 — COMMENTED** [review]
Thanks for this PR, left only a small comment

**Review by vctt94 — APPROVED** [review]
Thanks. LGTM
