### PR TITLE
Fix address not updating after receveing amount

### LINKED ISSUE #3104: [receive tx] Address reuse
When receiving decred in an address, it shouldn't still be shown on the receive tab, for avoiding address reuse. Which is not the case right now

### PR DESCRIPTION
**Pull request by vctt94**
closes #3104

### CODE REVIEW

File: app/actions/TransactionActions.js [hunk 1]
```diff
@@ -46,6 +47,22 @@ function checkAccountsToUpdate(txs, accountsToUpdate) {
   return accountsToUpdate;
 }
 
+// getNewAccountAddresses get accounts which received new inputs and get
+// new addresses for avoiding reuse.
+export const getNewAccountAddresses = (txs) => (dispatch) => {
+  const acctAddressUpdated = [];
+  txs.forEach((tx) => {
```
Comment (amassarwi) [inline app/actions/TransactionActions.js:54]: no need to `{`

**Review by amassarwi — APPROVED** [review]
lgtm

**Review by alexlyp — APPROVED** [review]
