### PR TITLE
[governance] Display cast votes error

### LINKED ISSUE #3385: Cast vote errors not displayed
If an error occurs while attempting to cast an individual proposal vote the error will be returned in the `CastVoteReply`.  The http response code will still be 200.  Decrediton does not currently display the individual `CastVoteReply` errors, which gives the appearance of votes being cast successfully even if they failed.  The `CastVoteReply` errors sould be displayed to the user.

```
// CastVoteReply contains the receipt for the cast vote.
type CastVoteReply struct {
	Ticket  string `json:"ticket"`  // Ticket ID
	Receipt string `json:"receipt"` // Server signature of client signature

	// The follwing fields will only be present if an error occurred
	// while attempting to cast the vote.
	ErrorCode    VoteErrorT `json:"errorcode,omitempty"`
	ErrorContext string     `json:"errorcontext,omitempty"`
}
```

### PR DESCRIPTION
**Pull request by victorgcramos**
This diff closes #3385, which reported an unhandled error on votes cast requests. We needed to parse the response and check for any CastVoteReply error on receipts response.

### CODE REVIEW

**Review by matheusd — APPROVED** [review]

File: app/actions/GovernanceActions.js [hunk 1]
```diff
@@ -686,7 +686,15 @@ export const updateVoteChoice = (
     });
 
     // cast vote into pi server
-    await pi.castVotes({ piURL, votes });
+    const response = await pi.castVotes({ piURL, votes });
+    const voteCastError = response.data.receipts.find(
+      (receipt) => receipt.error
```
Comment (amassarwi) [inline app/actions/GovernanceActions.js:691]:
```suggestion
      ({ error }) => error
```

File: app/actions/GovernanceActions.js [hunk 2]
```diff
@@ -686,7 +686,15 @@ export const updateVoteChoice = (
     });
 
     // cast vote into pi server
-    await pi.castVotes({ piURL, votes });
+    const response = await pi.castVotes({ piURL, votes });
+    const voteCastError = response.data.receipts.find(
```
Comment (amassarwi) [inline app/actions/GovernanceActions.js:690]:
```suggestion
    const { error } = response.data.receipts.find(
```

File: app/actions/GovernanceActions.js [hunk 3]
```diff
@@ -686,7 +686,15 @@ export const updateVoteChoice = (
...
+      (receipt) => receipt.error
+    );
+
+    if (voteCastError) {
```
Comment (amassarwi) [inline app/actions/GovernanceActions.js:694]:
```suggestion
    if (error) {
```

**Review by amassarwi — COMMENTED** [review]
LGTM, left some minor suggestions.

File: app/actions/GovernanceActions.js (hunk 2 above)
Comment (victorgcramos) [reply app/actions/GovernanceActions.js:690]: If there are no receipts errors, this will try to access the prop `error` of undefined, see?

Comment (amassarwi) [reply app/actions/GovernanceActions.js:690]: you could add `|| {}` at the end of this _find_ function.

Comment (amassarwi) [reply app/actions/GovernanceActions.js:690]: ie `find(.....) || {};`

Comment (victorgcramos) [reply app/actions/GovernanceActions.js:690]: I think this is a bit confusing in terms of readability

**Review by amassarwi — APPROVED** [review]
