### PR TITLE
[GetStarted] Don't ask for pwd on watching only wallets

### LINKED ISSUE #2842: watching only wallet: Asked for password to discover accounts.
This must be due to something recent. When creating a watching only wallet I am asked to provide a passphrase which does not exist to discover accounts that can't be discovered. Afterwards I am unable to open the wallet at all with the error: 
```
react_devtools_backend.js:6 Error: 12 UNIMPLEMENTED: wallet.Unlock: watching only wallet: watching wallets can not be unlocked
```

discoveraccounts

### PR DESCRIPTION
**Pull request by matheusd**
Fix #2842

### CODE REVIEW

**Review by vctt94 — APPROVED** [review]
LGTM

File: app/components/views/GetStartedPage/hooks.js [hunk 1]
```diff
@@ -145,12 +145,13 @@ export const useGetStarted = () => {
...
         const { selectedWallet } = context;
         const { passPhrase } = context;
+        const isWatchingOnly = selectedWallet.value.isWatchingOnly;
         const hasPassPhrase = !!passPhrase;
         onStartWallet(selectedWallet, hasPassPhrase)
           .then((discoverAccountsComplete) => {
             setSelectedWallet(selectedWallet);
             const { passPhrase } = context;
-            if (!discoverAccountsComplete && !passPhrase) {
+            if (!discoverAccountsComplete && !passPhrase && !isWatchingOnly) {
```
Comment (JoeGruffins) [inline app/components/views/GetStartedPage/hooks.js:154]: I guess you also need to add isTrezor, because it still asks me for the password if I check trezor but not wathing only.

Comment (matheusd) [reply app/components/views/GetStartedPage/hooks.js:154]: Trezors are also considered watching only wallets, and I tested the PR with a physical trezor and wasn't asked. What exactly was the flow you used that made you hit it?

**Review by JoeGruffins — APPROVED** [review]
No longer being asked.

File: app/components/views/GetStartedPage/hooks.js (hunk 1 above)
Comment (matheusd) [reply app/components/views/GetStartedPage/hooks.js]: Updated to account for trezor wallets.
