### PR TITLE
Fix: Transfer tx showing wrong receiver account

### LINKED ISSUE #2919: transfer tx can show wrong account
If making a transfer tx between accounts, decrediton can show it as 

image 

even though it was a transfer for other account and it just had change to default

### PR DESCRIPTION
**Pull request by amassarwi**
This diff fixes an issue with transfer fee tx showing wrong receiver account, as these txs may have multiple
outputs, this commit picks the account which corresponds to the first not change output.

---

Closes #2919

### CODE REVIEW

File: app/selectors.js [hunk 1]
```diff
@@ -593,9 +603,14 @@ export const transactionNormalizer = createSelector(
         const amount = credit.getAmount();
         const address = credit.getAddress();
         const creditedAccount = credit.getAccount();
-        creditedAccountName = getAccountName(creditedAccount);
+        const currentCreditedAccountName = getAccountName(creditedAccount);
+        // If we find crediton account differnt than default, then we pick
+        // it as receiver
+        if (currentCreditedAccountName !== "default" || !creditedAccountName) {
```
Comment (vctt94) [inline app/selectors.js:609]: I believe this shouldn't be hard coded for default. Changing the account name, from default -> "whatever" would break it, or using a different account

**Review by vctt94 — CHANGES_REQUESTED** [review]

File: app/selectors.js (hunk 1 above)
Comment (amassarwi) [reply app/selectors.js]: updated

**Review by vctt94 — APPROVED** [review]
LGTM!

**Comment by xaur** [comment]
Depending on how "change output" is determined, this may or may not break with randomized UTXO selection added in https://github.com/decred/dcrwallet/pull/1914
