### PR TITLE
Fix dcrd db upgrade not being notify

### LINKED ISSUE #2689: Provide feedback on dcrd db upgrade progress
dcrd has two long-running database migrations from 1.5.2 -> master:

```
2020-10-07 09:52:23.095 [INF] CHAN: Reindexing block information in the database.  This may take a while...
...
2020-10-07 09:52:37.243 [INF] CHAN: Done migrating block index.  Total entries: 491379 in 14.147s
```

```
2020-10-07 09:52:38.618 [INF] CHAN: Upgrading database to version 7...
...
2020-10-07 09:53:57.978 [INF] CHAN: Done upgrading database in 1m19.361s.
```

Decrediton isn't providing feedback on these at the moment, simply reports "Starting Daemon..."

Screenshot from 2020-10-07 09-59-30

### LINKED ISSUE #2781: [launch] Decrediton tries to launch dcrd more than once
On regular mode, if I go to the logs page, for example, when going back, decrediton will fail with resource temporary unavaible, because it tries to launch dcrd again.

### PR DESCRIPTION
**Pull request by vctt94**
This PR fixes #2689. Fixes #2781 and it also re-add the dcrd logs which were missing from the linear progress component.

### CODE REVIEW

**Comment by jholdstock** [comment]
Tried this PR with a testnet upgrade and a mainnet upgrade, looks great.

File: app/actions/DaemonActions.js [hunk 1]
```diff
@@ -579,6 +585,12 @@ export const getDcrdLogs = () => {
     });
 };
 
+export const getDcrdLastLineLogs = () => () => new Promise((resolve, reject) => {
```
Comment (amassarwi) [inline app/actions/DaemonActions.js:588]:
```suggestion
export const getDcrdLastLineLogs = () => () => new Promise((resolve, reject) => 
```

then closing `}` can go

**Review by amassarwi — APPROVED** [review]
LGTM, left one tiny suggestion.

**Review by alexlyp — APPROVED** [review]
