### PR TITLE
[daemon] Add corrupted error and give user option to delete blockchain data to fix

### LINKED ISSUE #1388: [daemon] Allow a way for blockchain data erasing
Due to users randomly hitting corrupted blockchains, we should show the user a button to erase the blockchain data and let them restart the download.

### PR DESCRIPTION
**Pull request by alexlyp**
Closes #1388

### CODE REVIEW

File: app/main_dev/ipc.js [hunk 1]
```diff
@@ -29,6 +29,22 @@ export const getAvailableWallets = (network) => {
   return availableWallets;
 };
 
+export const deleteDaemon = (appData, testnet) => {
+  let removeDaemonDirectory = getDcrdPath();
+  if (appData) removeDaemonDirectory = appData;
+  let removeDaemonDirectoryData = path.join(removeDaemonDirectory, "data", testnet ? "simnet" : "mainnet");
```
Comment (matheusd) [inline app/main_dev/ipc.js]: I believe this needs to be `testnet` instead of `simnet`

File: app/components/views/FatalErrorPage.js [hunk 2]
```diff
@@ -20,13 +25,23 @@ class FatalErrorPage extends React.Component {
...
+                <Aux>
+                  <div className="fatal-error-reset-blockchain">
+                    <T id="fatal.suggestion.corrupted" m="This error means your blockchain data has somehow become corrupted.  Typically, this is caused by a sector on the HDD/SDD that went bad and its built-in SMART didn't repair it, or the more likely case, there was a memory issue which corrupted the data.  To resolve, you must delete your blockchain data and re-download.  Press the button below to complete the process. When you restart Decrediton, it will automatically begin your blockchain download. Please come to our support channel on slack/matrix/discord/rocketchat to get advice about running disk utilities. " />
+                  </div>
+                  <RemoveDaemonButton
+                    className="fatal-remove-button"
+                    modalTitle={<T id="fatal.removeConfirmModal.title" m="Remove daemon data"/>}
+                    modalContent={<T id="fatal.removeConfirmModal.content" m="Warning this action is permanent! Please make sure you want to remove your blockchain data before proceeding."/>}
```
Comment (matheusd) [inline app/components/views/FatalErrorPage.js]: Ok, final note: Add a note to the effect of: "Decrediton will automatically shutdown after deleting the folder. Please manually restart it afterwards" to let users know that the app shutdown will happen.

Comment (alexlyp) [reply app/components/views/FatalErrorPage.js]: Good call, sec
