### PR TITLE
[governance] Add the new treasury balance

### LINKED ISSUE #3675: incorrect treasury balance
It's not a big deal but the treasury balance on the governance page is only showing the balance of the legacy treasury.  Perhaps it should be the legacy and new decentralized treasury combined.

image

### PR DESCRIPTION
**Pull request by alexlyp**
Close #3675

### CODE REVIEW

File: app/actions/ClientActions.js [hunk 1]
```diff
@@ -751,21 +751,43 @@ export const copySeedToClipboard = (mnemonic) => (dispatch) => {
...
+        decimalPart += "0".repeat(8 - decimalPart.length);
+        legacyTreasuryBalance = integerPart + decimalPart;
+      });
+    let newTreasuryBalance = 0;
+    await da.getTreasuryInfo(dURL).then((treasuryInfo) => {
+      const unspentTreasury = treasuryInfo["data"]["balance"];
+      if (!unspentTreasury) return;
+      newTreasuryBalance = unspentTreasury;
+    });
+    console.log(legacyTreasuryBalance, newTreasuryBalance);
```
Comment (matheusd) [inline app/actions/ClientActions.js:779]: extra console.log

**Review by matheusd — APPROVED** [review]
