### PR TITLE
display RPC errors

### LINKED ISSUE #162: need to display startRPC errors
Currently if you hit invalid auth or something you get no feedback on what is wrong.

### PR DESCRIPTION
**Pull request by jolan**
Closes #162.

### CODE REVIEW

File: app/components/GetStarted.js [hunk 1]
```diff
@@ -254,6 +255,7 @@ class Home extends Component{
           <Step>
             <StepLabel>Start RPC Concensus</StepLabel>
             <StepContent>
+              <ShowError error={startRpcError} />
               {}
```
Comment (alexlyp) [inline app/components/GetStarted.js]: Can you define a new const for 
startRpc = (
<div>
  <ShowError>
</div>
);
then in put the startRpc in the curly brackets there.

Basically the same way it is done for the other steps

Comment (jolan) [inline app/components/GetStarted.js]: Done.  Also added the progress indicator.
